java_test(
    name = "ExampleTest",
    srcs = ["ExampleTest.java"],
    test_class = "ExampleTest",
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java:example",
        "@junit_junit",
    ],
)
